env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:react/recommended
  - plugin:jest/recommended
parser: typescript-eslint-parser
parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
  - prettier
rules:
  no-console: off
  prettier/prettier: error
settings:
  react:
    version: 16.5
