env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:react/recommended
  - plugin:jest/recommended
parser: typescript-eslint-parser
parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
  - prettier
  - typescript
rules:
  no-console: off
  prettier/prettier: error
  typescript/no-unused-vars: error
settings:
  react:
    version: 16.5
overrides:
  files:
    - '**/*.ts'
  parser: typescript-eslint-parser
  rules:
    typescript/no-undef: off
