--liquibase formatted sql

--changeset dore:1
CREATE TABLE users(
  userid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar UNIQUE ,
  password varchar
);

CREATE TABLE entries(
	entryid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userid int references users(userid),
	event varchar,
	lastoccurrence date,
	frequency interval DAY
);

CREATE TABLE "session" (
  "sid" varchar NOT NULL COLLATE "default",
	"sess" json NOT NULL,
	"expire" timestamp(6) NOT NULL
)
WITH (OIDS=FALSE);
ALTER TABLE "session" ADD CONSTRAINT "session_pkey" PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE;
