CREATE TABLE users(
  userid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar UNIQUE ,
  password varchar
);

CREATE TABLE entries(
	entryid int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	userid int references users(userid),
	event varchar,
	lastoccurrence date,
	frequency interval DAY
);

